### ISSUE TITLE
Fix all League search strings

### ISSUE THREAD

**Issue by DeathbyToast** [DeathbyToast/PvP_IVs#119]
Does not find GL rank 35 Carbink: https://pvpivs.com/searchStr.html?mon=Carbink&cp=All&r=207-35-10-10_f_f

![image](https://github.com/DeathbyToast/PvP_IVs/assets/68164168/c372cf08-a8a4-43ea-867c-d60bc38db3ef)

![image](https://github.com/DeathbyToast/PvP_IVs/assets/68164168/f0e6f63d-a9c6-4881-a239-8157144e050f)

But individual GL string finds r35 Carbink: https://pvpivs.com/searchStr.html?mon=Carbink&cp=1500&r=35_f_f

![image](https://github.com/DeathbyToast/PvP_IVs/assets/68164168/19b4f88d-9588-40b1-b371-2974d8e2b89f)

And LL r207 can be found individually too: https://pvpivs.com/searchStr.html?mon=Carbink&cp=500&r=207_f_f

![image](https://github.com/DeathbyToast/PvP_IVs/assets/68164168/7cf93b5e-2bf8-48af-9e9b-c4afb7775c41)

**Comment by igor-ruivo** [comment]
just wondering if your base stats are correct for all pokémon? in this case, Carbink?
i've done a small debug and i've noticed some wrong base stats (atk, def, hp) values for some pokémon, when comparing with pvpoke's gamemaster file. for instance, bulbasaur's family.

this leads to incorrect cps and hps being calculated in the "outputStr" step.

but it's weird because in pvp ivs page, the base values are correct. it's just that they appear wrong while debugging them on the search string page.

**Comment by DeathbyToast** [comment]
Observation: Both GL r35 and All Leagues set only to find GL r35 strings are identical:
https://pvpivs.com/searchStrTest.html?mon=Carbink&cp=All&r=0-35-10-10_f_f
https://pvpivs.com/searchStr.html?mon=Carbink&cp=1500&r=35_f_f

Bug is only introduced when second league is added

**Comment by DeathbyToast** [comment]
Observation: Combined All Leagues string omits any CPs above Little League cutoff (500CP), likely related to maxCP being set to 500, 500, 500, 0, 0 (should be 500, 1500) for: https://pvpivs.com/searchStrTest.html?mon=Carbink&cp=All&r=207-35-10-10_f_f

Added TODO comment to mark where maxCP is set, need to keep investigating

**Comment by DeathbyToast** [comment]
Also realized my rank35 Carbink is level 31, so it won't be found by default settings. But setting All Leagues string to L1-35 still doesn't have it show up: https://pvpivs.com/searchStrTest.html?mon=Carbink&cp=All&r=207-35-10-10_f_f&sl=35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1

Notice how even though it has been explicitly set to find up to L35 it doesn't load anything above 500CP, per maxCP observation from before. Interestingly, setting Levels to only find above Little League results in string working properly, as if it is an individual league search string again

**Comment by DeathbyToast** [comment]
Pushed some code updates, and have been able to get the string to work for top 5 LL and top 5 GL, but changing it to top 50 LL and top 5 GL breaks it again for some reason. Still trying to figure out why: 

https://pvpivs.com/searchStrTest.html?mon=Carbink&cp=All&r=5-5-10-10_f_f
https://pvpivs.com/searchStrTest.html?mon=Carbink&cp=All&r=50-5-10-10_f_f
