### ISSUE TITLE
Add a "what level is this" page

### ISSUE THREAD

**Issue by irilyth** [DeathbyToast/PvP_IVs#123]
A very lean page that just let you enter the IVs and CP of a pokemon, and told you what level it was, would be a nifty thing to have. No strong opinions about the UI, although I suppose if it was easy to use the same dropdowns and text input system as the rankings page (with a fourth field for CP), and let you enter multiple ones if you wanted to, that would make sense.

(IMHO something more complicated, like letting you optionally specify the current CP on the rankings page, would be harder to use; but if someone can come up with a clean interface for that, and it doesn't seem to clutter things up unnecessarily, then hey. But I kinda feel like a separate, super-simple page just for this would make the most sense.)

**Comment by matthewyu01** [comment]
@DeathbyToast Could I work on this even though you already assigned it to yourself? I made the same thing on my own since the ones online don't have the newest Pokemon.

**Comment by DeathbyToast** [comment]
Sure @matthewyu01 all I ask is that it is in the style of the other pages of the website. Probably best to take one of the existing pages and strip out the excess code to use as a template.

I had envisioned something with only a few inputs, the textbox for the mon name and the IV inputs (much like what exists on the single mon ranks page today) but without the table being generated or the shadow checkbox, etc. Also take in CP and spit out the level
