### ISSUE TITLE
Fix Clicking Highlighted Rows in Main Out Table Adds Duplicates

### ISSUE THREAD

**Issue by isalazar14** [DeathbyToast/PvP_IVs#55]
Clicking an already highlighted row (or the corresponding un-highlighted version of the same row) in the main table adds it as a new highlighted entry in the out table, as well as in the input table and family evos widgets.

**Comment by isalazar14** [comment]
Initial thought was that clicking a highlighted row should deselect/remove it from main out table and other widgets. 
Second thought was that it should do nothing.
Last thought was that if duplicating the entry is the intended effect, then it would be good to have an obvious way to remove the entry, like an "x" or trash icon next to the highlighted row. (The input table already allows removal of the entries via the minus button, but could be good to have an icon next to the highlighted rows as well)

**Comment by DeathbyToast** [comment]
@isalazar14 Thanks for the report! I hadn't actually thought about a user clicking on the highlighted rows in the table, but I've now not only fixed that case, but I've also added a check to ensure that the exact IVs the user is trying to add don't already exist in the top. You can see this functionality by going to [this link](https://pvpivs.com/?mon=Venusaur&r=10&cp=1500&f=0&min=1&max=40&set=000000&fel=1500&mA=119.7&mD=112.6&mHP=113&IVs=1_15_8) and trying to add the 9th rank IVs again. It should give a fairly descriptive error message on the main page (as well as more verbose errors in the console -- right click + Inspect will open the console). Let me know if we can mark this as resolved once you've had a chance to test this out!

**Comment by isalazar14** [comment]
@DeathbyToast Thanks for the quick turnaround! The duplicate issue is resolved, and the new warnings are clear. That said, clicking on the un-highlighted row corresponding to already selected rows creates duplicate warnings, which can't be removed (without refreshing the page), and which push down the page elements below.

**Comment by DeathbyToast** [comment]
@isalazar14 I've resolved the duplicate error message issue, and am going to close this out as resolved. But feel free to re-open if this needs more attention!
