### ISSUE TITLE
Remove awesomplete from searchStrings and refactor

### ISSUE THREAD

**Issue by DeathbyToast** [DeathbyToast/PvP_IVs#62]

**Comment by TheMagicNacho** [comment]
Is anything replacing awesomeplete? Or is the functionality going away completely?

**Comment by DeathbyToast** [comment]
@TheMagicNacho So this is actually already live on the rankings page (I've removed Awesomplete and replaced it with native HTML 5 instead for the autocomplete functionality), I just need to do this across the rest of the pages on the site but haven't taken the time to do so yet (have had limited time to work on this, and have been focused on other areas of the site instead).

Have you noticed any issues with the new autocomplete on the main rankings page?

**Comment by TheMagicNacho** [comment]
No issues. The main page looks like it's running smoothly!
You wanna close this issue?
