### ISSUE TITLE
Fix Rank Filter Functionality

### ISSUE THREAD

**Issue by DeathbyToast** [DeathbyToast/PvP_IVs#68]
Reported by TitanTrainers15 8527 8131 1902#4930 in #bugs on Jan 16, 2022.

**Comment by mglerner** [comment]
The specific example was:
"""I'm trying to churn through walreins, and I think there's bug. my 5/9/5 should have (I think! though maybe I'm wrong) stats of 114.473, 113.249, 151. But it doesn't show up on this page: https://pvpivs.com/?mon=Walrein&r=41&cp=1500&mA=114.45&mD=113&mHP=148"""

**Comment by DeathbyToast** [comment]
Changed the site such that the decimals setting now also adjusts the "step" inside of these filters. The problem was being caused when you tried to filter the stats to two decimal places but the filter input was hardcoded to only accept one decimal of precision. Now it will accept as many decimals of precision as the overall website is set to. Please let me know if this issue still gives you trouble and I can continue investigating!
